import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  SafeAreaView,
  StatusBar,
  Alert,
  Platform,
  Image,
} from "react-native";
import { useState, useEffect } from "react";
import Share from "react-native-share";
import RNFS from "react-native-fs";
import RNHTMLtoPDF from "react-native-html-to-pdf";
import {
  updateInvoicePdfPath,
  getClinicSettings,
  getFullInvoice,
  getAllInvoices,
} from "./../../database";

import BASE from "./../../constants/colors";

const COLORS = {
  ...BASE,
  textMuted: "#9AAFAC",
  billHeader: "#2E7D72",
  billHeaderText: "#FFFFFF",
  patientBg: "#F0F7F6",
  tableHeadBg: "#E8F2F0",
  statusDot: "#6B8B88",
  shareLogBadgeBg: "#D6EAE7",
  shareLogBadgeText: "#2E7D72",
};

const EMPTY_INV = {
  no: "",
  invoiceDate: "",
  dueDate: "",
  patient: { name: "", id: "" },
  service: { description: "", type: "", amount: 0, items: [] },
  totalAmount: 0,
  discount: 0,
  payable: 0,
  totalPaid: 0,
  extraPaid: 0,
  balanceDue: 0,
  paymentStatus: "",
  billingType: "",
  payments: [],
  insuranceClause: "",
  physiotherapist: "",
  note: "",
};

function DashedDivider() {
  return <View style={styles.dashedDivider} />;
}

function ShareAction({ icon, label, onPress }: any) {
  return (
    <TouchableOpacity
      style={styles.shareAction}
      onPress={onPress}
      activeOpacity={0.75}
    >
      <Text style={styles.shareActionIcon}>{icon}</Text>
      <Text style={styles.shareActionLabel}>{label}</Text>
    </TouchableOpacity>
  );
}

export default function EBillGeneratedScreen({ navigation, route }: any) {
  const {
    showBack,
    pdfPath,
    patient: routePatient,
    billing: routeBilling,
    amount: routeAmount,
    note: routeNote,
    therapist: routeTherapist,
  } = route.params || {};

  const [clinicSettings, setClinicSettings] = useState<any>(null);
  const [loadedInvoice, setLoadedInvoice] = useState<any>(null);

  useEffect(() => {
    (async () => {
      try {
        const settings = await getClinicSettings();
        setClinicSettings(settings);
      } catch {}
      if (!routeBilling) {
        try {
          const list = await getAllInvoices();
          if (list.length > 0) {
            const full = await getFullInvoice(list[0].id);
            if (full) setLoadedInvoice(full);
          }
        } catch {}
      }
    })();
  }, []);

  const note = routeNote || "";

  const sqlInv = loadedInvoice && {
    no: loadedInvoice.invoiceNo,
    invoiceDate: loadedInvoice.invoiceDate,
    dueDate: loadedInvoice.dueDate,
    patient: { name: loadedInvoice.patientName, id: loadedInvoice.patientReg },
    service: {
      description:
        loadedInvoice.items.map((i: any) => i.name).join(" + ") || "—",
      type: loadedInvoice.billingType,
      amount: loadedInvoice.total,
      items: loadedInvoice.items.map((i: any) => ({
        name: i.name,
        qty: i.qty,
        unit: i.unit || "",
        amount: i.unitPrice * i.qty,
      })),
    },
    totalAmount: loadedInvoice.total,
    discount: loadedInvoice.discount,
    payable: loadedInvoice.payable,
    totalPaid: loadedInvoice.totalPaid,
    extraPaid: loadedInvoice.extraPaid || 0,
    balanceDue: loadedInvoice.balanceDue,
    paymentStatus: loadedInvoice.status,
    billingType: loadedInvoice.billingType,
    payments: loadedInvoice.payments,
    insuranceClause:
      clinicSettings?.insuranceClause ||
      "This is a valid e-bill generated by VedaMotion Care. To verify its authenticity, please email vedamotioncare@gmail.com quoting the invoice number. A confirmation will be sent after the bill is verified against our records.",
    physiotherapist:
      loadedInvoice.therapist ||
      clinicSettings?.physiotherapist ||
      "Dr. Yash Pratihasta, PT",
    note: loadedInvoice.note,
  };

  const inv = routeBilling
    ? {
        no: routeBilling.invoiceNo,
        invoiceDate: routeBilling.date,
        dueDate: routeBilling.due,
        patient: { name: routePatient.name, id: routePatient.reg },
        service: {
          description: routeBilling.service,
          type: routeBilling.type,
          amount: routeAmount.total,
          items: routeBilling.items || [],
        },
        totalAmount: routeAmount.total,
        discount: routeAmount.discount,
        payable: routeAmount.payable,
        totalPaid: routeAmount.totalPaid,
        extraPaid: routeAmount.extraPaid || 0,
        balanceDue: routeAmount.balanceDue,
        paymentStatus: routeAmount.status,
        billingType: routeBilling.type,
        payments: routeAmount.payments,
        insuranceClause:
          clinicSettings?.insuranceClause ||
          "This is a valid e-bill generated by VedaMotion Care. To verify its authenticity, please email vedamotioncare@gmail.com quoting the invoice number. A confirmation will be sent after the bill is verified against our records.",
        physiotherapist:
          routeTherapist ||
          clinicSettings?.physiotherapist ||
          "Dr. Yash Pratihasta, PT",
        note,
      }
    : sqlInv || EMPTY_INV;

  const generatePdf = async (): Promise<string> => {
    const fmt = (n: number) => "\u20B9" + Number(n).toLocaleString("en-IN");
    const badgeStyle = (status: string) => {
      const map: Record<string, string> = {
        Paid: "background:#E8F5EC;color:#27AE60",
        "Advance Paid": "background:#EBF5FB;color:#2980B9",
        "Partial Paid": "background:#F4ECF7;color:#8E44AD",
        "Over Paid": "background:#E8F8F5;color:#1ABC9C",
        Due: "background:#FEF0E6;color:#D35400",
      };
      return map[status] || "background:#E8F5EC;color:#27AE60";
    };
    const logoHtml = clinicSettings?.logoUri
      ? `<img src="${clinicSettings.logoUri}" style="width:52px;height:52px;border-radius:12px;object-fit:cover" />`
      : "🌿";
    const itemsHtml =
      inv.service.items && inv.service.items.length > 0
        ? inv.service.items
            .map(
              (it: any) =>
                `<tr><td style="width:46%">${
                  it.name
                }</td><td class="center" style="width:15%;color:#7A9490">${
                  it.qty || ""
                }</td><td class="center" style="width:15%;color:#7A9490">${
                  it.unit || ""
                }</td><td class="amt-cell" style="width:24%">${fmt(
                  it.amount,
                )}</td></tr>`,
            )
            .join("")
        : `<tr><td style="width:46%">${
            inv.service.description
          }</td><td class="center" style="width:15%;color:#7A9490"></td><td class="center" style="width:15%;color:#7A9490"></td><td class="amt-cell" style="width:24%">${fmt(
            inv.totalAmount,
          )}</td></tr>`;

    const h = [
      "<html><head><style>",
      "@page{margin:0}",
      "*{margin:0;padding:0;box-sizing:border-box}",
      "body{font-family:Helvetica Neue,Helvetica,Arial,sans-serif;color:#1A2E2B;font-size:12px;line-height:1.5;width:100%}",
      ".page{padding:0 20px 20px}",
      ".clinic-hdr{background:#2E7D72;padding:14px 20px;display:flex;gap:10px;align-items:flex-start}",
      ".logo{width:52px;height:52px;background:#FFF;display:flex;align-items:center;justify-content:center;font-size:26px;flex-shrink:0}",
      ".clinic-info{flex:1}",
      ".clinic-name{font-size:22px;font-weight:800;color:#FFF;letter-spacing:-0.3px}",
      ".tagline{font-size:12px;color:rgba(255,255,255,0.8);font-style:italic;margin:3px 0 0}",
      ".contact{font-size:11px;color:rgba(255,255,255,0.7);margin:6px 0 0;line-height:16px}",
      ".label-row{background:#1F5C56;padding:8px 20px;display:flex;justify-content:space-between;align-items:center}",
      ".label{font-size:11px;font-weight:800;color:#FFF;letter-spacing:1.5px}",
      ".inv-no{font-size:13px;font-weight:700;color:rgba(255,255,255,0.9)}",
      ".dates{padding:10px 20px;display:flex;justify-content:space-between;border-bottom:1px solid #E2EDEB}",
      ".date-text{font-size:12px;color:#1A2E2B;font-weight:500}",
      ".patient-box{padding:10px 20px;border-bottom:1px solid #E2EDEB}",
      ".patient-name{font-size:16px;font-weight:800;color:#1A2E2B}",
      ".patient-id{font-size:12px;color:#7A9490;margin:4px 0 0}",
      "table{width:100%;border-collapse:collapse;margin:10px 20px;width:calc(100% - 40px)}",
      "th{padding:8px 10px;text-align:left;font-size:11px;font-weight:700;color:#2E7D72;letter-spacing:0.5px;background:#E8F2F0;border-bottom:2px solid #2E7D72}",
      ".amt-cell{text-align:right}",
      ".center{text-align:center}",
      "td{padding:8px 10px;font-size:13px;color:#1A2E2B;border-bottom:1px solid #E2EDEB}",
      ".amount-box{margin:10px 20px;border:1px solid #E2EDEB;padding:12px 16px}",
      ".amt-row{display:flex;justify-content:space-between;padding:6px 0}",
      ".amt-label{font-size:13px;color:#7A9490}",
      ".amt-val{font-size:13px;color:#1A2E2B}",
      ".amt-bold{font-size:16px;font-weight:800;color:#1A2E2B}",
      ".hr{border:none;border-top:1px solid #C8DEDA;margin:10px 0}",
      ".status-row{display:flex;justify-content:space-between;align-items:center;padding:6px 0}",
      ".badge{padding:4px 14px;font-size:12px;font-weight:700}",
      ".note-box{margin:10px 20px;padding:10px 14px;border:1px solid #E2EDEB}",
      ".note-label{font-size:11px;font-weight:700;color:#1A7866;text-transform:uppercase;letter-spacing:0.5px;margin-bottom:6px}",
      ".note-text{font-size:13px;color:#1A2E2B;line-height:20px}",
      ".insurance{margin:10px 20px;padding:10px 14px;border:1px solid #E2EDEB;background:#FEF8EC}",
      ".ins-text{font-size:12px;color:#7A5C10;line-height:20px;font-style:italic}",
      ".footer{font-size:11px;color:#9AAFAC;text-align:center;padding:10px 20px;line-height:18px;border-top:1px solid #E2EDEB;margin:4px 20px 0}",
      "</style></head><body>",
      '<div class="page">',

      '<div class="clinic-hdr">',
      '<div class="logo">' + logoHtml + "</div>",
      '<div class="clinic-info">',
      '<div class="clinic-name">' +
        (clinicSettings?.clinicName || "VedaMotion Care") +
        "</div>",
      '<div class="tagline">' +
        (clinicSettings?.tagline || "Where Every Move Heals") +
        "</div>",
      '<div class="contact">' +
        (clinicSettings?.phone || "+91 8875115254") +
        " · " +
        (clinicSettings?.email || "vedamotioncare@gmail.com") +
        " ·<br>" +
        (clinicSettings?.website || "www.vedamotioncare.in") +
        "</div>",
      "</div></div>",

      '<div class="label-row">',
      '<span class="label">E-BILL / INVOICE</span>',
      '<span class="inv-no">' + inv.no + "</span></div>",

      '<div class="dates">',
      '<span class="date-text">Invoice Date: ' + inv.invoiceDate + "</span>",
      '<span class="date-text">Due Date: ' + inv.dueDate + "</span></div>",

      '<div class="patient-box">',
      '<div class="patient-name">' + inv.patient.name + "</div>",
      '<div class="patient-id">Patient ID: ' + inv.patient.id + "</div>",
      '<div class="patient-id" style="margin-top:4px">Treating Physiotherapist: ' +
        inv.physiotherapist +
        "</div></div>",

      '<table cellpadding="0" cellspacing="0"><tr>',
      '<th style="width:46%">DESCRIPTION</th>',
      '<th class="center" style="width:15%">QTY</th>',
      '<th class="center" style="width:15%">UNIT</th>',
      '<th class="amt-cell" style="width:24%">AMOUNT</th>',
      "</tr>" + itemsHtml + "</table>",

      '<div class="amount-box">',
      '<div class="amt-row"><span class="amt-label">Total Amount</span><span class="amt-val">' +
        fmt(inv.totalAmount) +
        "</span></div>",
      inv.discount > 0
        ? '<div class="amt-row"><span class="amt-label">Discount</span><span class="amt-val">– ' +
          fmt(inv.discount) +
          "</span></div>"
        : "",
      '<hr class="hr">',
      '<div class="amt-row"><span class="amt-bold">Payable Amount</span><span class="amt-bold">' +
        fmt(inv.payable) +
        "</span></div>",
      '<div class="amt-row"><span class="amt-label">Total Paid</span><span class="amt-val">' +
        fmt(inv.totalPaid) +
        "</span></div>",
      inv.totalPaid > 0
        ? '<div class="amt-row"><span class="amt-label">' +
          (inv.billingType === "Package" ? "Advance Paid" : "Extra Paid") +
          '</span><span class="amt-val">' +
          fmt(inv.billingType === "Package" ? inv.totalPaid : inv.extraPaid) +
          "</span></div>"
        : "",
      '<div class="amt-row"><span class="amt-label">Balance Due</span><span class="amt-val">' +
        fmt(inv.balanceDue) +
        "</span></div>",
      '<div class="status-row"><span class="amt-label">Payment Status</span><span class="badge" style="' +
        badgeStyle(inv.paymentStatus) +
        '">' +
        inv.paymentStatus +
        "</span></div>",
      "</div>",

      inv.note
        ? '<div class="note-box"><div class="note-label">Note / Remarks</div><div class="note-text">' +
          inv.note +
          "</div></div>"
        : "",

      '<div class="insurance">',
      '<div class="ins-text">' + inv.insuranceClause + "</div>",
      "</div>",

      '<div class="footer">' +
        (clinicSettings?.clinicName || "VedaMotion Care") +
        " · Service & Payment Policy applies · " +
        (clinicSettings?.tagline || "Where Every Move Heals") +
        "</div>",

      "</div></body></html>",
    ].join("");

    const now = new Date();
    const dd = String(now.getDate()).padStart(2, "0");
    const mm = String(now.getMonth() + 1).padStart(2, "0");
    const hh = String(now.getHours()).padStart(2, "0");
    const min = String(now.getMinutes()).padStart(2, "0");
    const ss = String(now.getSeconds()).padStart(2, "0");
    const pdf = await RNHTMLtoPDF.convert({
      html: h,
      width: 595,
      height: 842,
      margin: 0,
      fileName: `Invoice_${inv.no.replace(
        /\//g,
        "-",
      )}_${dd}-${mm} & time(${hh} ${min} ${ss})`,
    });

    if (!pdf.filePath) {
      throw new Error("Failed to generate PDF.");
    }

    try {
      await updateInvoicePdfPath(inv.no, pdf.filePath);
    } catch {
      // silent
    }

    return pdf.filePath;
  };

  const ensurePdf = async (): Promise<string> => {
    if (pdfPath) {
      try {
        const exists = await RNFS.exists(pdfPath.replace("file://", ""));
        if (exists) return pdfPath;
      } catch {
        // file check failed, regenerate
      }
    }
    return await generatePdf();
  };

  const handleShare = async () => {
    try {
      const path = await ensurePdf();
      const shareUrl = path.startsWith("file://") ? path : `file://${path}`;
      await Share.open({
        title: "Share Invoice",
        urls: [shareUrl],
        type: "application/pdf",
        failOnCancel: false,
      });
    } catch (error: any) {
      if (error?.message !== "User did not share") {
        Alert.alert("Error", error?.message || "Something went wrong.");
      }
    }
  };

  // const handleDownload = async () => {
  //   try {
  //     const path = await ensurePdf();
  //     const fileName = `Invoice_${inv.no.replace(/\//g, '-')}.pdf`;
  //     const sourcePath = path.replace('file://', '');

  //     // Always save to a writable directory first (works on all Android versions)
  //     const destDir =
  //       Platform.OS === 'android'
  //         ? (Platform.Version as number) >= 30
  //           ? RNFS.ExternalDirectoryPath
  //           : RNFS.DownloadDirectoryPath
  //         : RNFS.DocumentDirectoryPath;
  //     const destPath = `${destDir}/${fileName}`;
  //     const exists = await RNFS.exists(destPath);
  //     if (exists) await RNFS.unlink(destPath);
  //     await RNFS.copyFile(sourcePath, destPath);
  //     try {
  //       await RNFS.scanFile(destPath);
  //     } catch {}

  //     if (Platform.OS === 'android' && (Platform.Version as number) >= 30) {
  //       // Android 11+ can't write to user-visible Downloads directly.
  //       // The file is saved to the app's external dir (safe). Now open the share
  //       // sheet so user can pick "Save to Files" → Downloads.
  //       const shareUrl = destPath.startsWith('file://')
  //         ? destPath
  //         : `file://${destPath}`;
  //       await Share.open({
  //         urls: [shareUrl],
  //         type: 'application/pdf',
  //         failOnCancel: false,
  //       });
  //       Alert.alert(
  //         'Downloaded',
  //         'PDF saved. Use Save to Files from the share sheet to store it in Downloads.',
  //       );
  //     } else {
  //       Alert.alert(
  //         'Downloaded',
  //         `PDF saved to ${
  //           Platform.OS === 'android' ? 'Downloads' : 'Documents'
  //         } as ${fileName}`,
  //       );
  //     }
  //   } catch (error: any) {
  //     if (error?.message !== 'User did not share') {
  //       Alert.alert('Error', error?.message || 'Failed to download PDF.');
  //     }
  //   }
  // };

  return (
    <SafeAreaView style={styles.safe}>
      <StatusBar barStyle="light-content" backgroundColor={COLORS.teal} />

      {/* Header */}
      <View style={styles.header}>
        {showBack && (
          <TouchableOpacity
            style={styles.backBtn}
            activeOpacity={0.8}
            onPress={() => navigation.goBack()}
          >
            <Text style={styles.backArrow}>←</Text>
          </TouchableOpacity>
        )}
        <View>
          <Text style={styles.headerTitle}>E-Bill Generated</Text>
          <Text style={styles.headerSub}>{inv.no}</Text>
        </View>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.container}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.stageHint}>
          The same e-bill, shared at different stages — before, during, or after
          the patient settles up. Share is available at every stage.
        </Text>
        {/* ── INVOICE DOCUMENT ── */}
        <View style={styles.billCard}>
          {/* Clinic header */}
          <View style={styles.billClinicHeader}>
            <View style={styles.clinicLogoBox}>
              {clinicSettings?.logoUri ? (
                <Image
                  source={{ uri: clinicSettings.logoUri }}
                  style={styles.clinicLogoImage}
                />
              ) : (
                <Text style={styles.clinicLogoEmoji}>🌿</Text>
              )}
            </View>
            <View style={styles.clinicInfo}>
              <Text style={styles.clinicName}>
                {clinicSettings?.clinicName || "VedaMotion Care"}
              </Text>
              <Text style={styles.clinicTagline}>
                {clinicSettings?.tagline || "Where Every Move Heals"}
              </Text>
              <Text style={styles.clinicContact}>
                {clinicSettings?.phone} · {clinicSettings?.email} ·{"\n"}
                {clinicSettings?.website}
              </Text>
            </View>
          </View>

          {/* E-Bill label row */}
          <View style={styles.billLabelRow}>
            <Text style={styles.billLabel}>E-BILL / INVOICE</Text>
            <Text style={styles.billNo}>{inv.no}</Text>
          </View>

          {/* Dates */}
          <View style={styles.billDatesRow}>
            <Text style={styles.billDateText}>
              Invoice Date: {inv.invoiceDate}
            </Text>
            <Text style={styles.billDateText}>Due Date: {inv.dueDate}</Text>
          </View>

          {/* Patient */}
          <View style={styles.patientBox}>
            <Text style={styles.patientBoxName}>{inv.patient.name}</Text>
            <Text style={styles.patientBoxId}>
              Patient ID: {inv.patient.id}
            </Text>
            <Text style={styles.patientBoxId}>
              Treating Physiotherapist: {inv.physiotherapist}
            </Text>
          </View>

          {/* Service table */}
          <View style={styles.table}>
            <View style={styles.tableHead}>
              <Text style={[styles.tableHeadCell, { flex: 1.5 }]}>
                DESCRIPTION
              </Text>
              <Text
                style={[
                  styles.tableHeadCell,
                  { flex: 0.5, textAlign: "center" },
                ]}
              >
                QTY
              </Text>
              <Text
                style={[
                  styles.tableHeadCell,
                  { flex: 0.5, textAlign: "center" },
                ]}
              >
                UNIT
              </Text>
              <Text
                style={[
                  styles.tableHeadCell,
                  { flex: 0.8, textAlign: "right" },
                ]}
              >
                AMOUNT
              </Text>
            </View>
            {(inv.service.items && inv.service.items.length > 0
              ? inv.service.items
              : [{ name: inv.service.description, amount: inv.service.amount }]
            ).map((it: any, idx: number) => (
              <View key={idx} style={styles.tableRow}>
                <Text style={[styles.tableCell, { flex: 1.5 }]}>
                  {it.name || it.description}
                </Text>
                <Text
                  style={[
                    styles.tableCell,
                    {
                      flex: 0.5,
                      textAlign: "center",
                      color: COLORS.textSecondary,
                    },
                  ]}
                >
                  {it.qty || ""}
                </Text>
                <Text
                  style={[
                    styles.tableCell,
                    {
                      flex: 0.5,
                      textAlign: "center",
                      color: COLORS.textSecondary,
                    },
                  ]}
                >
                  {it.unit || ""}
                </Text>
                <Text
                  style={[styles.tableCell, { flex: 0.8, textAlign: "right" }]}
                >
                  ₹{(it.amount || 0).toLocaleString("en-IN")}
                </Text>
              </View>
            ))}
          </View>

          {/* Amount breakdown */}
          <View style={styles.amountBox}>
            <View style={styles.amountRow}>
              <Text style={styles.amountLabel}>Total Amount</Text>
              <Text style={styles.amountValue}>
                ₹{inv.totalAmount.toLocaleString("en-IN")}
              </Text>
            </View>
            {inv.discount > 0 && (
              <View style={styles.amountRow}>
                <Text style={styles.amountLabel}>Discount</Text>
                <Text style={styles.amountValue}>
                  – ₹{inv.discount.toLocaleString("en-IN")}
                </Text>
              </View>
            )}
            <DashedDivider />
            <View style={styles.amountRow}>
              <Text style={styles.amountLabelBold}>Payable Amount</Text>
              <Text style={styles.amountValueBold}>
                ₹{inv.payable.toLocaleString("en-IN")}
              </Text>
            </View>
            <View style={styles.amountRow}>
              <Text style={styles.amountLabel}>Total Paid</Text>
              <Text style={styles.amountValue}>
                ₹{inv.totalPaid.toLocaleString("en-IN")}
              </Text>
            </View>
            {inv.totalPaid > 0 ? (
              <View style={styles.amountRow}>
                <Text style={styles.amountLabel}>
                  {inv.billingType === "Package"
                    ? "Advance Paid"
                    : "Extra Paid"}
                </Text>
                <Text style={styles.amountValue}>
                  ₹
                  {(inv.billingType === "Package"
                    ? inv.totalPaid
                    : inv.extraPaid
                  ).toLocaleString("en-IN")}
                </Text>
              </View>
            ) : null}
            <View style={styles.amountRow}>
              <Text style={styles.amountLabel}>Balance Due</Text>
              <Text style={styles.amountValue}>
                ₹{inv.balanceDue.toLocaleString("en-IN")}
              </Text>
            </View>
            <View style={styles.amountStatusRow}>
              <Text style={styles.amountLabel}>Payment Status</Text>
              <View
                style={[
                  styles.dueBadge,
                  inv.paymentStatus === "Over Paid" && {
                    backgroundColor: COLORS.cyanLight,
                  },
                  inv.paymentStatus === "Advance Paid" && {
                    backgroundColor: COLORS.skyBlueLight,
                  },
                  inv.paymentStatus === "Partial Paid" && {
                    backgroundColor: COLORS.violetLight,
                  },
                ]}
              >
                <Text
                  style={[
                    styles.dueBadgeText,
                    inv.paymentStatus === "Over Paid" && {
                      color: COLORS.cyan,
                    },
                    inv.paymentStatus === "Advance Paid" && {
                      color: COLORS.skyBlue,
                    },
                    inv.paymentStatus === "Partial Paid" && {
                      color: COLORS.violet,
                    },
                  ]}
                >
                  {inv.paymentStatus}
                </Text>
              </View>
            </View>
          </View>

          {/* Note / Remarks */}
          {inv.note ? (
            <View style={styles.noteSection}>
              <Text style={styles.noteLabel}>Note / Remarks</Text>
              <Text style={styles.noteText}>{inv.note}</Text>
            </View>
          ) : null}

          {/* Insurance clause */}
          <View style={styles.insuranceBanner}>
            <View style={styles.insuranceBar} />
            <Text style={styles.insuranceText}>{inv.insuranceClause}</Text>
          </View>

          {/* Signature line */}
          {/* <View style={styles.signatureRow}>
            <View style={styles.signatureBlock}>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Patient Signature</Text>
            </View>
            <View style={styles.signatureBlock}>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Clinic Stamp / Sign</Text>
            </View>
          </View> */}

          {/* Footer */}
          <Text style={styles.billFooter}>
            {clinicSettings?.clinicName || "VedaMotion Care"} · Service &
            Payment Policy applies ·{" "}
            {clinicSettings?.tagline || "Where Every Move Heals"}
          </Text>
        </View>
        {/* Share actions */}
        <View style={styles.shareRow}>
          <ShareAction icon="📤" label="Share" onPress={handleShare} />
        </View>
        {!showBack && (
          <TouchableOpacity
            style={styles.generateBtn}
            activeOpacity={0.85}
            onPress={() => navigation.navigate("Dashboard")}
          >
            <Text style={styles.generateBtnText}>Go to Dashboard</Text>
          </TouchableOpacity>
        )}
        {/* Share log */}
        {/* <Text style={styles.shareLogTitle}>SHARE LOG</Text>
        <View style={styles.shareLogCard}>
          {SHARE_LOG.map((entry, idx) => (
            <View key={idx} style={styles.shareLogRow}>
              <View style={styles.shareLogInfo}>
                <Text style={styles.shareLogChannel}>{entry.channel}</Text>
                <Text style={styles.shareLogDate}>{entry.date}</Text>
              </View>
              <View style={styles.shareLogBadge}>
                <Text style={styles.shareLogBadgeText}>{entry.status}</Text>
              </View>
            </View>
          ))}
        </View> */}
        {/* Edit invoice */}
        {/* <TouchableOpacity
          style={styles.editBtn}
          onPress={handleEdit}
          activeOpacity={0.8}>
          <Text style={styles.editBtnText}>Edit Invoice</Text>
        </TouchableOpacity> */}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.teal },

  header: {
    backgroundColor: COLORS.teal,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  backArrow: { fontSize: 18, color: "#FFF", lineHeight: 22 },
  headerTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: COLORS.headerText,
    letterSpacing: -0.4,
  },
  headerSub: { fontSize: 13, color: COLORS.headerSub, marginTop: 2 },

  scroll: { flex: 1, backgroundColor: COLORS.bg },
  container: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 24,
    gap: 10,
  },

  // Stage selector
  stageGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  stageBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.card,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    width: "47%",
  },
  stageDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.statusDot,
  },
  stageDotActive: { backgroundColor: COLORS.teal },
  stageBtnText: { fontSize: 13, fontWeight: "600", color: COLORS.textPrimary },
  stageHint: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: "center",
    lineHeight: 18,
  },

  // ── Bill card ──
  billCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  billClinicHeader: {
    backgroundColor: COLORS.billHeader,
    padding: 12,
    flexDirection: "row",
    gap: 10,
    alignItems: "flex-start",
  },
  clinicLogoBox: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  clinicLogoEmoji: { fontSize: 26 },
  clinicLogoImage: { width: 52, height: 52, borderRadius: 12 },
  clinicInfo: { flex: 1 },
  clinicName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#FFF",
    letterSpacing: -0.3,
  },
  clinicTagline: {
    fontSize: 12,
    color: "rgba(255,255,255,0.8)",
    fontStyle: "italic",
    marginTop: 0,
  },
  clinicContact: {
    fontSize: 11,
    color: "rgba(255,255,255,0.7)",
    marginTop: 2,
    lineHeight: 14,
  },

  billLabelRow: {
    backgroundColor: COLORS.tealDark,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  billLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: "#FFF",
    letterSpacing: 1,
  },
  billNo: { fontSize: 12, fontWeight: "700", color: "rgba(255,255,255,0.85)" },

  billDatesRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  billDateText: { fontSize: 12, color: COLORS.textPrimary, fontWeight: "500" },

  patientBox: {
    margin: 8,
    backgroundColor: COLORS.patientBg,
    borderRadius: 10,
    padding: 8,
  },
  patientBoxName: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  patientBoxId: { fontSize: 12, color: COLORS.textSecondary, marginTop: 3 },

  // Table
  table: { marginHorizontal: 8, marginBottom: 4 },
  tableHead: {
    backgroundColor: COLORS.tableHeadBg,
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    marginBottom: 2,
  },
  tableHeadCell: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.teal,
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  tableCell: { fontSize: 13, color: COLORS.textPrimary, lineHeight: 18 },

  // Amount box
  amountBox: {
    margin: 8,
    backgroundColor: COLORS.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 10,
    gap: 6,
  },
  amountRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  amountLabel: { fontSize: 13, color: COLORS.textSecondary },
  amountValue: { fontSize: 13, color: COLORS.textPrimary },
  amountLabelBold: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  amountValueBold: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.textPrimary,
  },
  amountStatusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dueBadge: {
    backgroundColor: COLORS.orangeLight,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  dueBadgeText: { fontSize: 12, fontWeight: "700", color: COLORS.orange },

  dashedDivider: {
    height: 1,
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: COLORS.dashed,
    marginVertical: 2,
  },

  // Note
  noteBtn: {
    marginHorizontal: 12,
    marginTop: 8,
    borderWidth: 1.5,
    borderColor: COLORS.billHeader,
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: "center",
  },
  noteBtnText: { fontSize: 14, fontWeight: "700", color: COLORS.billHeader },
  noteBanner: {
    marginHorizontal: 12,
    marginTop: 8,
    backgroundColor: COLORS.tealBg,
    borderRadius: 10,
    padding: 12,
  },
  noteBannerLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.billHeader,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  noteBannerText: {
    fontSize: 13,
    color: COLORS.textPrimary,
    lineHeight: 18,
  },

  // Insurance
  insuranceBanner: {
    margin: 8,
    backgroundColor: COLORS.amberBg,
    borderRadius: 10,
    padding: 10,
    flexDirection: "row",
    gap: 8,
  },
  insuranceBar: {
    width: 3,
    borderRadius: 4,
    backgroundColor: COLORS.amberBorder,
    flexShrink: 0,
  },
  insuranceText: {
    flex: 1,
    fontSize: 12,
    color: COLORS.amberText,
    lineHeight: 18,
    fontStyle: "italic",
  },

  physioText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginHorizontal: 16,
    marginTop: 4,
  },
  physioName: { fontWeight: "700", color: COLORS.textPrimary },

  // Signature
  signatureRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 8,
    gap: 20,
  },
  signatureBlock: { flex: 1, alignItems: "center" },
  signatureLine: {
    width: "100%",
    height: 1,
    backgroundColor: COLORS.textSecondary,
    marginBottom: 6,
  },
  signatureLabel: { fontSize: 11, color: COLORS.textSecondary },

  billFooter: {
    fontSize: 11,
    color: COLORS.textMuted,
    textAlign: "center",
    paddingHorizontal: 8,
    paddingBottom: 10,
    paddingTop: 6,
    lineHeight: 16,
  },

  // Share row
  shareRow: {
    flexDirection: "row",
    gap: 10,
  },
  shareAction: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  shareActionIcon: { fontSize: 22 },
  shareActionLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.textPrimary,
  },

  // Tip banner
  tipBanner: {
    backgroundColor: COLORS.amberBg,
    borderRadius: 12,
    padding: 14,
    flexDirection: "row",
    gap: 10,
  },
  tipBar: {
    width: 3,
    borderRadius: 4,
    backgroundColor: COLORS.amberBorder,
    flexShrink: 0,
  },
  tipText: { flex: 1, fontSize: 13, color: COLORS.amberText, lineHeight: 20 },

  // Share log
  shareLogTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.teal,
    letterSpacing: 1.1,
    marginBottom: -2,
  },
  shareLogCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  shareLogRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
  },
  shareLogInfo: { gap: 3 },
  shareLogChannel: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  shareLogDate: { fontSize: 12, color: COLORS.textSecondary },
  shareLogBadge: {
    backgroundColor: COLORS.shareLogBadgeBg,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  shareLogBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.shareLogBadgeText,
  },

  // Edit button
  editBtn: {
    borderWidth: 1.5,
    borderColor: COLORS.teal,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
  },
  editBtnText: { fontSize: 15, fontWeight: "700", color: COLORS.teal },

  // Dashboard button
  generateBtn: {
    backgroundColor: COLORS.teal,
    borderRadius: 16,
    paddingVertical: 17,
    alignItems: "center",
    shadowColor: COLORS.teal,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
  },
  generateBtnText: {
    fontSize: 16,
    fontWeight: "800",
    color: "#FFF",
  },

  // Note / Remarks
  noteSection: {
    marginHorizontal: 8,
    backgroundColor: COLORS.tealBg,
    borderRadius: 10,
    padding: 10,
    marginTop: 6,
  },
  noteLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.teal,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  noteText: {
    fontSize: 13,
    color: COLORS.textPrimary,
    lineHeight: 18,
  },
});
