import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  SafeAreaView,
  StatusBar,
  Alert,
  Platform,
} from 'react-native';
import Share from 'react-native-share';
import RNFS from 'react-native-fs';

const COLORS = {
  teal: '#2E7D72',
  tealDark: '#1F5C56',
  tealLight: '#D6EAE7',
  tealBg: '#EBF4F2',
  bg: '#EFF5F4',
  card: '#FFFFFF',
  billHeader: '#2E7D72',
  billHeaderText: '#FFFFFF',
  textPrimary: '#1A2E2B',
  textSecondary: '#7A9490',
  textMuted: '#9AAFAC',
  border: '#E2EDEB',
  dashed: '#C8DEDA',
  amber: '#A07820',
  amberBg: '#FEF8EC',
  amberBorder: '#D4A82A',
  amberText: '#7A5C10',
  red: '#C0392B',
  redLight: '#FDECEB',
  patientBg: '#F0F7F6',
  tableHeadBg: '#E8F2F0',
  headerText: '#FFFFFF',
  headerSub: 'rgba(255,255,255,0.75)',
  statusDot: '#6B8B88',
  shareLogBadgeBg: '#D6EAE7',
  shareLogBadgeText: '#2E7D72',
  green: '#27AE60',
  greenLight: '#E8F5EC',
};

const PAYMENT_STAGES = [
  {label: 'Pending', active: true},
  {label: 'Partial', active: false},
  {label: 'Paid', active: false},
];

const SHARE_LOG = [
  {channel: 'WhatsApp', date: '21 Jun, 10:42 AM', status: 'Advance Paid'},
];

const INVOICE = {
  no: 'VMC-INV-260621-03',
  invoiceDate: '21 Jun 2026',
  dueDate: '21 Jun 2026',
  patient: {name: 'Priya Sharma', id: 'VMCPTREG-0124'},
  service: {
    description: '10-Visit Package — Knee Rehab',
    type: 'Package',
    amount: 1300,
    items: [{name: '10-Visit Package — Knee Rehab', amount: 1300}],
  },
  totalAmount: 1300,
  discount: 100,
  payable: 1200,
  totalPaid: 0,
  extraPaid: 0,
  balanceDue: 1200,
  paymentStatus: 'Pending',
  insuranceClause:
    'This is a valid e-bill generated by VedaMotion Care. To verify its authenticity, please email vedamotioncare@gmail.com quoting the invoice number. A confirmation will be sent after the bill is verified against our records.',
  physiotherapist: 'Dr. Yash Pratihasta, PT',
  note: '',
};

function DashedDivider() {
  return <View style={styles.dashedDivider} />;
}

function ShareAction({icon, label, onPress}: any) {
  return (
    <TouchableOpacity
      style={styles.shareAction}
      onPress={onPress}
      activeOpacity={0.75}>
      <Text style={styles.shareActionIcon}>{icon}</Text>
      <Text style={styles.shareActionLabel}>{label}</Text>
    </TouchableOpacity>
  );
}

export default function EBillGeneratedScreen({navigation, route}: any) {
  const {
    pdfPath,
    patient: routePatient,
    billing: routeBilling,
    amount: routeAmount,
    note: routeNote,
    therapist: routeTherapist,
  } = route.params || {};

  const note = routeNote || '';

  const inv = routeBilling
    ? {
        no: routeBilling.invoiceNo,
        invoiceDate: routeBilling.date,
        dueDate: routeBilling.due,
        patient: {name: routePatient.name, id: routePatient.reg},
        service: {
          description: routeBilling.service,
          type: routeBilling.type,
          amount: routeAmount.total,
          items: routeBilling.items || [],
        },
        totalAmount: routeAmount.total,
        discount: routeAmount.discount,
        payable: routeAmount.payable,
        totalPaid: routeAmount.totalPaid,
        extraPaid: routeAmount.extraPaid || 0,
        balanceDue: routeAmount.balanceDue,
        paymentStatus: routeAmount.status,
        payments: routeAmount.payments,
        insuranceClause:
          'This is a valid e-bill generated by VedaMotion Care. To verify its authenticity, please email vedamotioncare@gmail.com quoting the invoice number. A confirmation will be sent after the bill is verified against our records.',
        physiotherapist: routeTherapist || 'Dr. Yash Pratihasta, PT',
        note,
      }
    : INVOICE;

  const handleShare = async () => {
    if (!pdfPath) {
      Alert.alert('Error', 'PDF not found. Please generate the invoice first.');
      return;
    }
    try {
      const shareUrl = pdfPath.startsWith('file://')
        ? pdfPath
        : `file://${pdfPath}`;
      await Share.open({
        title: 'Share Invoice',
        urls: [shareUrl],
        type: 'application/pdf',
        failOnCancel: false,
      });
    } catch (error: any) {
      if (error?.message !== 'User did not share') {
        Alert.alert('Error', error?.message || 'Something went wrong.');
      }
    }
  };

  const handleDownload = async () => {
    if (!pdfPath) {
      Alert.alert('Error', 'PDF not found. Please generate the invoice first.');
      return;
    }
    try {
      const destDir =
        Platform.OS === 'android'
          ? RNFS.DownloadDirectoryPath
          : RNFS.DocumentDirectoryPath;
      const fileName = `Invoice_${inv.no.replace(/\//g, '-')}.pdf`;
      const destPath = `${destDir}/${fileName}`;
      await RNFS.copyFile(pdfPath.replace('file://', ''), destPath);
      Alert.alert('Downloaded', `PDF saved to Downloads folder as ${fileName}`);
    } catch (error: any) {
      Alert.alert('Error', error?.message || 'Failed to download PDF.');
    }
  };

  // const handleEdit = () => navigation.goBack();

  return (
    <SafeAreaView style={styles.safe}>
      <StatusBar barStyle="light-content" backgroundColor={COLORS.teal} />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity
          style={styles.backBtn}
          activeOpacity={0.8}
          onPress={() => navigation.goBack()}>
          <Text style={styles.backArrow}>←</Text>
        </TouchableOpacity>
        <View>
          <Text style={styles.headerTitle}>E-Bill Generated</Text>
          <Text style={styles.headerSub}>{inv.no}</Text>
        </View>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.container}
        showsVerticalScrollIndicator={false}>
        <Text style={styles.stageHint}>
          The same e-bill, shared at different stages — before, during, or after
          the patient settles up. Share is available at every stage.
        </Text>
        {/* ── INVOICE DOCUMENT ── */}
        <View style={styles.billCard}>
          {/* Clinic header */}
          <View style={styles.billClinicHeader}>
            <View style={styles.clinicLogoBox}>
              <Text style={styles.clinicLogoEmoji}>🌿</Text>
            </View>
            <View style={styles.clinicInfo}>
              <Text style={styles.clinicName}>VedaMotion Care</Text>
              <Text style={styles.clinicTagline}>Where Every Move Heals</Text>
              <Text style={styles.clinicContact}>
                +91 8875115254 · vedamotioncare@gmail.com ·{'\n'}
                www.vedamotioncare.in
              </Text>
            </View>
          </View>

          {/* E-Bill label row */}
          <View style={styles.billLabelRow}>
            <Text style={styles.billLabel}>E-BILL / INVOICE</Text>
            <Text style={styles.billNo}>{inv.no}</Text>
          </View>

          {/* Dates */}
          <View style={styles.billDatesRow}>
            <Text style={styles.billDateText}>
              Invoice Date: {inv.invoiceDate}
            </Text>
            <Text style={styles.billDateText}>Due Date: {inv.dueDate}</Text>
          </View>

          {/* Patient */}
          <View style={styles.patientBox}>
            <Text style={styles.patientBoxName}>{inv.patient.name}</Text>
            <Text style={styles.patientBoxId}>
              Patient ID: {inv.patient.id}
            </Text>
            <Text style={styles.patientBoxId}>
              Treating Physiotherapist: {inv.physiotherapist}
            </Text>
          </View>

          {/* Service table */}
          <View style={styles.table}>
            <View style={styles.tableHead}>
              <Text style={[styles.tableHeadCell, {flex: 2}]}>DESCRIPTION</Text>
              <Text
                style={[styles.tableHeadCell, {flex: 1, textAlign: 'center'}]}>
                TYPE
              </Text>
              <Text
                style={[styles.tableHeadCell, {flex: 1, textAlign: 'right'}]}>
                AMOUNT
              </Text>
            </View>
            {(inv.service.items && inv.service.items.length > 0
              ? inv.service.items
              : [{name: inv.service.description, amount: inv.service.amount}]
            ).map((it: any, idx: number) => (
              <View key={idx} style={styles.tableRow}>
                <Text style={[styles.tableCell, {flex: 2}]}>
                  {it.name || it.description}
                </Text>
                <Text
                  style={[
                    styles.tableCell,
                    {flex: 1, textAlign: 'center', color: COLORS.textSecondary},
                  ]}>
                  {inv.service.type}
                </Text>
                <Text style={[styles.tableCell, {flex: 1, textAlign: 'right'}]}>
                  ₹{(it.amount || 0).toLocaleString('en-IN')}
                </Text>
              </View>
            ))}
          </View>

          {/* Amount breakdown */}
          <View style={styles.amountBox}>
            <View style={styles.amountRow}>
              <Text style={styles.amountLabel}>Total Amount</Text>
              <Text style={styles.amountValue}>
                ₹{inv.totalAmount.toLocaleString('en-IN')}
              </Text>
            </View>
            {inv.discount > 0 && (
              <View style={styles.amountRow}>
                <Text style={styles.amountLabel}>Discount</Text>
                <Text style={styles.amountValue}>
                  – ₹{inv.discount.toLocaleString('en-IN')}
                </Text>
              </View>
            )}
            <DashedDivider />
            <View style={styles.amountRow}>
              <Text style={styles.amountLabelBold}>Payable Amount</Text>
              <Text style={styles.amountValueBold}>
                ₹{inv.payable.toLocaleString('en-IN')}
              </Text>
            </View>
            <View style={styles.amountRow}>
              <Text style={styles.amountLabel}>Total Paid</Text>
              <Text style={styles.amountValue}>
                ₹{inv.totalPaid.toLocaleString('en-IN')}
              </Text>
            </View>
            {inv.extraPaid > 0 ? (
              <View style={styles.amountRow}>
                <Text style={styles.amountLabel}>Extra Paid</Text>
                <Text style={styles.amountValue}>
                  ₹{inv.extraPaid.toLocaleString('en-IN')}
                </Text>
              </View>
            ) : inv.totalPaid > 0 ? (
              <View style={styles.amountRow}>
                <Text style={styles.amountLabel}>Advance Paid</Text>
                <Text style={styles.amountValue}>
                  ₹{inv.totalPaid.toLocaleString('en-IN')}
                </Text>
              </View>
            ) : null}
            <View style={styles.amountRow}>
              <Text style={styles.amountLabel}>Balance Due</Text>
              <Text style={styles.amountValue}>
                ₹{inv.balanceDue.toLocaleString('en-IN')}
              </Text>
            </View>
            <View style={styles.amountStatusRow}>
              <Text style={styles.amountLabel}>Payment Status</Text>
              <View
                style={[
                  styles.dueBadge,
                  inv.paymentStatus === 'Paid' && {
                    backgroundColor: COLORS.greenLight,
                  },
                  inv.paymentStatus === 'Partial' && {
                    backgroundColor: COLORS.amberBg,
                  },
                ]}>
                <Text
                  style={[
                    styles.dueBadgeText,
                    inv.paymentStatus === 'Paid' && {color: COLORS.green},
                    inv.paymentStatus === 'Partial' && {color: COLORS.amber},
                  ]}>
                  {inv.paymentStatus}
                </Text>
              </View>
            </View>
          </View>

          {/* Note / Remarks */}
          {inv.note ? (
            <View style={styles.noteSection}>
              <Text style={styles.noteLabel}>Note / Remarks</Text>
              <Text style={styles.noteText}>{inv.note}</Text>
            </View>
          ) : null}

          {/* Insurance clause */}
          <View style={styles.insuranceBanner}>
            <View style={styles.insuranceBar} />
            <Text style={styles.insuranceText}>{inv.insuranceClause}</Text>
          </View>

          {/* Signature line */}
          {/* <View style={styles.signatureRow}>
            <View style={styles.signatureBlock}>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Patient Signature</Text>
            </View>
            <View style={styles.signatureBlock}>
              <View style={styles.signatureLine} />
              <Text style={styles.signatureLabel}>Clinic Stamp / Sign</Text>
            </View>
          </View> */}

          {/* Footer */}
          <Text style={styles.billFooter}>
            VedaMotion Care · Service & Payment Policy applies · Where Every
            Move Heals
          </Text>
        </View>
        {/* Share actions */}
        <View style={styles.shareRow}>
          <ShareAction icon="⬇️" label="Download" onPress={handleDownload} />
          <ShareAction icon="📤" label="Share" onPress={handleShare} />
        </View>
        {/* Share log */}
        {/* <Text style={styles.shareLogTitle}>SHARE LOG</Text>
        <View style={styles.shareLogCard}>
          {SHARE_LOG.map((entry, idx) => (
            <View key={idx} style={styles.shareLogRow}>
              <View style={styles.shareLogInfo}>
                <Text style={styles.shareLogChannel}>{entry.channel}</Text>
                <Text style={styles.shareLogDate}>{entry.date}</Text>
              </View>
              <View style={styles.shareLogBadge}>
                <Text style={styles.shareLogBadgeText}>{entry.status}</Text>
              </View>
            </View>
          ))}
        </View> */}
        {/* Edit invoice */}
        {/* <TouchableOpacity
          style={styles.editBtn}
          onPress={handleEdit}
          activeOpacity={0.8}>
          <Text style={styles.editBtnText}>Edit Invoice</Text>
        </TouchableOpacity> */}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {flex: 1, backgroundColor: COLORS.teal},

  header: {
    backgroundColor: COLORS.teal,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  backArrow: {fontSize: 18, color: '#FFF', lineHeight: 22},
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.headerText,
    letterSpacing: -0.4,
  },
  headerSub: {fontSize: 13, color: COLORS.headerSub, marginTop: 2},

  scroll: {flex: 1, backgroundColor: COLORS.bg},
  container: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 36,
    gap: 14,
  },

  // Stage selector
  stageGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
  stageBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: COLORS.card,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    width: '47%',
  },
  stageDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: COLORS.statusDot,
  },
  stageDotActive: {backgroundColor: COLORS.teal},
  stageBtnText: {fontSize: 13, fontWeight: '600', color: COLORS.textPrimary},
  stageHint: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
  },

  // ── Bill card ──
  billCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 3},
    elevation: 3,
  },
  billClinicHeader: {
    backgroundColor: COLORS.billHeader,
    padding: 16,
    flexDirection: 'row',
    gap: 12,
    alignItems: 'flex-start',
  },
  clinicLogoBox: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  clinicLogoEmoji: {fontSize: 26},
  clinicInfo: {flex: 1},
  clinicName: {
    fontSize: 18,
    fontWeight: '800',
    color: '#FFF',
    letterSpacing: -0.3,
  },
  clinicTagline: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.8)',
    fontStyle: 'italic',
    marginTop: 2,
  },
  clinicContact: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 5,
    lineHeight: 16,
  },

  billLabelRow: {
    backgroundColor: COLORS.tealDark,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  billLabel: {fontSize: 11, fontWeight: '800', color: '#FFF', letterSpacing: 1},
  billNo: {fontSize: 12, fontWeight: '700', color: 'rgba(255,255,255,0.85)'},

  billDatesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  billDateText: {fontSize: 12, color: COLORS.textSecondary},

  patientBox: {
    margin: 12,
    backgroundColor: COLORS.patientBg,
    borderRadius: 10,
    padding: 12,
  },
  patientBoxName: {fontSize: 15, fontWeight: '800', color: COLORS.textPrimary},
  patientBoxId: {fontSize: 12, color: COLORS.textSecondary, marginTop: 3},

  // Table
  table: {marginHorizontal: 12, marginBottom: 4},
  tableHead: {
    backgroundColor: COLORS.tableHeadBg,
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 2,
  },
  tableHeadCell: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.teal,
    letterSpacing: 0.5,
  },
  tableRow: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  tableCell: {fontSize: 13, color: COLORS.textPrimary, lineHeight: 18},

  // Amount box
  amountBox: {
    margin: 12,
    backgroundColor: COLORS.card,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14,
    gap: 10,
  },
  amountRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  amountLabel: {fontSize: 13, color: COLORS.textSecondary},
  amountValue: {fontSize: 13, color: COLORS.textPrimary},
  amountLabelBold: {fontSize: 15, fontWeight: '800', color: COLORS.textPrimary},
  amountValueBold: {fontSize: 15, fontWeight: '800', color: COLORS.textPrimary},
  amountStatusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dueBadge: {
    backgroundColor: COLORS.redLight,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  dueBadgeText: {fontSize: 12, fontWeight: '700', color: COLORS.red},

  dashedDivider: {
    height: 1,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: COLORS.dashed,
    marginVertical: 2,
  },

  // Note
  noteBtn: {
    marginHorizontal: 12,
    marginTop: 8,
    borderWidth: 1.5,
    borderColor: COLORS.billHeader,
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
  },
  noteBtnText: {fontSize: 14, fontWeight: '700', color: COLORS.billHeader},
  noteBanner: {
    marginHorizontal: 12,
    marginTop: 8,
    backgroundColor: COLORS.tealBg,
    borderRadius: 10,
    padding: 12,
  },
  noteBannerLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.billHeader,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  noteBannerText: {
    fontSize: 13,
    color: COLORS.textPrimary,
    lineHeight: 18,
  },

  // Insurance
  insuranceBanner: {
    margin: 12,
    backgroundColor: COLORS.amberBg,
    borderRadius: 10,
    padding: 12,
    flexDirection: 'row',
    gap: 8,
  },
  insuranceBar: {
    width: 3,
    borderRadius: 4,
    backgroundColor: COLORS.amberBorder,
    flexShrink: 0,
  },
  insuranceText: {
    flex: 1,
    fontSize: 12,
    color: COLORS.amberText,
    lineHeight: 18,
    fontStyle: 'italic',
  },

  physioText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginHorizontal: 16,
    marginTop: 4,
  },
  physioName: {fontWeight: '700', color: COLORS.textPrimary},

  // Signature
  signatureRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 8,
    gap: 20,
  },
  signatureBlock: {flex: 1, alignItems: 'center'},
  signatureLine: {
    width: '100%',
    height: 1,
    backgroundColor: COLORS.textSecondary,
    marginBottom: 6,
  },
  signatureLabel: {fontSize: 11, color: COLORS.textSecondary},

  billFooter: {
    fontSize: 11,
    color: COLORS.textMuted,
    textAlign: 'center',
    paddingHorizontal: 12,
    paddingBottom: 16,
    paddingTop: 8,
    lineHeight: 16,
  },

  // Share row
  shareRow: {
    flexDirection: 'row',
    gap: 10,
  },
  shareAction: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  shareActionIcon: {fontSize: 22},
  shareActionLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.textPrimary,
  },

  // Tip banner
  tipBanner: {
    backgroundColor: COLORS.amberBg,
    borderRadius: 12,
    padding: 14,
    flexDirection: 'row',
    gap: 10,
  },
  tipBar: {
    width: 3,
    borderRadius: 4,
    backgroundColor: COLORS.amberBorder,
    flexShrink: 0,
  },
  tipText: {flex: 1, fontSize: 13, color: COLORS.amberText, lineHeight: 20},

  // Share log
  shareLogTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.teal,
    letterSpacing: 1.1,
    marginBottom: -2,
  },
  shareLogCard: {
    backgroundColor: COLORS.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  shareLogRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 14,
  },
  shareLogInfo: {gap: 3},
  shareLogChannel: {fontSize: 15, fontWeight: '700', color: COLORS.textPrimary},
  shareLogDate: {fontSize: 12, color: COLORS.textSecondary},
  shareLogBadge: {
    backgroundColor: COLORS.shareLogBadgeBg,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  shareLogBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.shareLogBadgeText,
  },

  // Edit button
  editBtn: {
    borderWidth: 1.5,
    borderColor: COLORS.teal,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: 'center',
  },
  editBtnText: {fontSize: 15, fontWeight: '700', color: COLORS.teal},

  // Note / Remarks
  noteSection: {
    marginHorizontal: 12,
    backgroundColor: COLORS.tealBg,
    borderRadius: 10,
    padding: 12,
    marginTop: 8,
  },
  noteLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.teal,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  noteText: {
    fontSize: 13,
    color: COLORS.textPrimary,
    lineHeight: 18,
  },
});
