import React from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  ScrollView,
  StyleSheet,
  SafeAreaView,
  StatusBar,
  Alert,
} from 'react-native';
import RNHTMLtoPDF from 'react-native-html-to-pdf';

const COLORS = {
  teal: '#2E7D72',
  tealDark: '#1F5C56',
  tealLight: '#D6EAE7',
  bg: '#EFF5F4',
  card: '#FFFFFF',
  textPrimary: '#1A2E2B',
  textSecondary: '#7A9490',
  textMuted: '#9AAFAC',
  border: '#E8F0EF',
  dashed: '#C8DEDA',
  amber: '#A07820',
  amberBg: '#FEF8EC',
  amberBorder: '#D4A82A',
  headerText: '#FFFFFF',
  headerSub: 'rgba(255,255,255,0.75)',
};

function SectionCard({title, onEdit, children}: any) {
  return (
    <View style={styles.card}>
      <View style={styles.cardHeader}>
        <Text style={styles.cardTitle}>{title}</Text>
        <TouchableOpacity
          style={styles.editBtn}
          onPress={onEdit}
          activeOpacity={0.7}>
          <Text style={styles.editIcon}>✏️</Text>
          <Text style={styles.editText}>Edit</Text>
        </TouchableOpacity>
      </View>
      {children}
    </View>
  );
}

function Row({label, value, bold, dimLabel}: any) {
  return (
    <View style={styles.row}>
      <Text style={[styles.rowLabel, dimLabel && styles.rowLabelDim]}>
        {label}
      </Text>
      <Text style={[styles.rowValue, bold && styles.rowValueBold]}>
        {value}
      </Text>
    </View>
  );
}

function DashedDivider() {
  return <View style={styles.dashedDivider} />;
}

export default function ReviewInvoiceScreen({navigation, route}: any) {
  const {patient, billing, amount} = route.params || {
    patient: {name: '', reg: ''},
    billing: {invoiceNo: '', date: '', due: '', type: '', service: ''},
    amount: {
      total: 0,
      discount: 0,
      payable: 0,
      payments: [],
      totalPaid: 0,
      balanceDue: 0,
      status: 'Unpaid',
      isAdvance: false,
    },
  };

  const handleEdit = (section: string) => {
    Alert.alert('Edit', `Going back to edit ${section}…`);
  };

  const handleGenerate = async () => {
    try {
      const h = [
        '<html><head><style>',
        'body{font-family:Helvetica Neue,Helvetica,Arial,sans-serif;padding:40px;color:#1A2E2B}',
        'h1{color:#2E7D72;font-size:24px;margin-bottom:4px}',
        '.s{color:#7A9490;font-size:14px;margin-bottom:24px}',
        'table{width:100%;border-collapse:collapse;margin-top:20px}',
        'th,td{padding:10px 12px;text-align:left;border-bottom:1px solid #E2EDEB}',
        'th{color:#2E7D72;font-weight:600}',
        '.t{font-weight:bold;font-size:16px}',
        '.f{margin-top:40px;color:#7A9490;font-size:12px;text-align:center}',
        '</style></head><body>',
        '<h1>Vaidya Multispecialty Clinic</h1>',
        '<div class="s">' +
          billing.invoiceNo +
          ' \u2022 ' +
          billing.date +
          '</div>',
        '<table>',
        '<tr><th>Patient</th><td>' + patient.name + '</td></tr>',
        '<tr><th>Reg No.</th><td>' + patient.reg + '</td></tr>',
        '<tr><th>Service</th><td>' + billing.service + '</td></tr>',
        '<tr><th>Total</th><td>\u20B9' + amount.total + '</td></tr>',
        '<tr><th>Discount</th><td>-\u20B9' + amount.discount + '</td></tr>',
        '<tr class="t"><th>Payable</th><td>\u20B9' +
          amount.payable +
          '</td></tr>',
        '<tr><th>Advance Paid</th><td>\u20B9' +
          amount.payments[0].amount +
          ' (' +
          amount.payments[0].method +
          ')</td></tr>',
        '<tr class="t"><th>Balance Due</th><td>\u20B9' +
          amount.balanceDue +
          '</td></tr>',
        '</table>',
        '<div class="f">Generated by Vaidya Multispecialty Clinic App</div>',
        '</body></html>',
      ].join('');

      const pdf = await RNHTMLtoPDF.convert({
        html: h,
        fileName: `Invoice_${billing.invoiceNo}`,
        directory: 'Documents',
      });

      if (!pdf.filePath) {
        Alert.alert('Error', 'Failed to generate PDF. Please try again.');
        return;
      }

      navigation.navigate('EBillGenerated', {
        pdfPath: pdf.filePath,
        patient,
        billing,
        amount,
      });
    } catch (error: any) {
      if (error?.message !== 'User did not share') {
        Alert.alert(
          'Error',
          error?.message || 'Something went wrong while generating PDF.',
        );
      }
    }
  };

  return (
    <SafeAreaView style={styles.safe}>
      <StatusBar barStyle="light-content" backgroundColor={COLORS.teal} />

      {/* Header */}
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} activeOpacity={0.8}>
          <Text style={styles.backArrow}>←</Text>
        </TouchableOpacity>
        <View>
          <Text style={styles.headerTitle}>Review Invoice</Text>
          <Text style={styles.headerSub}>Before generating PDF</Text>
        </View>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.container}
        showsVerticalScrollIndicator={false}>
        {/* Info banner */}
        <View style={styles.banner}>
          <View style={styles.bannerBar} />
          <Text style={styles.bannerText}>
            This is the in-app summary before the e-bill is generated. Tap any
            section's pencil to jump back and edit — nothing is final until you
            tap Generate PDF.
          </Text>
        </View>

        {/* Patient section */}
        <SectionCard title="Patient" onEdit={() => handleEdit('Patient')}>
          <Text style={styles.patientName}>{patient.name}</Text>
          <Text style={styles.patientReg}>{patient.reg}</Text>
        </SectionCard>

        {/* Billing section */}
        <SectionCard title="Billing" onEdit={() => handleEdit('Billing')}>
          <Row label="Invoice No." value={billing.invoiceNo} dimLabel />
          <Row
            label="Date / Due"
            value={`${billing.date} / ${billing.due}`}
            dimLabel
          />
          <Row label="Type" value={billing.type} dimLabel />
          <Row label="Service" value={billing.service} dimLabel />
        </SectionCard>

        {/* Amount section */}
        <SectionCard title="Amount" onEdit={() => handleEdit('Amount')}>
          <Row
            label="Total Amount"
            value={`₹${amount.total.toLocaleString('en-IN')}`}
            dimLabel
          />
          <Row
            label="Discount"
            value={`– ₹${amount.discount.toLocaleString('en-IN')}`}
            dimLabel
          />

          <DashedDivider />

          <Row
            label="Payable Amount"
            value={`₹${amount.payable.toLocaleString('en-IN')}`}
            bold
          />

          <View style={styles.spacer} />

          {amount.payments.map((p: any, i: any) => (
            <Row
              key={i}
              label={`Paid — ${p.method}${
                p.mode === 'advance' ? ' (advance)' : ''
              }`}
              value={`₹${p.amount.toLocaleString('en-IN')}`}
              dimLabel
            />
          ))}
          <Row
            label="Balance Due"
            value={`₹${amount.balanceDue.toLocaleString('en-IN')}`}
            dimLabel
          />

          <View style={styles.statusRow}>
            <Text style={styles.statusLabel}>Payment Status</Text>
            <View style={styles.statusBadge}>
              <Text style={styles.statusBadgeText}>{amount.status}</Text>
            </View>
          </View>
        </SectionCard>
      </ScrollView>

      {/* Sticky bottom */}
      <View style={styles.bottomBar}>
        <TouchableOpacity
          style={styles.generateBtn}
          activeOpacity={0.85}
          onPress={handleGenerate}>
          <Text style={styles.generateBtnText}>Generate PDF & Share</Text>
        </TouchableOpacity>
        <Text style={styles.bottomNote}>
          You can still edit and re-share after this step.
        </Text>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {flex: 1, backgroundColor: COLORS.teal},

  // Header
  header: {
    backgroundColor: COLORS.teal,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 18,
    gap: 12,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  backArrow: {fontSize: 18, color: '#FFF', lineHeight: 22},
  headerTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: COLORS.headerText,
    letterSpacing: -0.4,
  },
  headerSub: {fontSize: 13, color: COLORS.headerSub, marginTop: 2},

  // Scroll
  scroll: {flex: 1, backgroundColor: COLORS.bg},
  container: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 20,
    gap: 12,
  },

  // Banner
  banner: {
    backgroundColor: COLORS.amberBg,
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    gap: 10,
  },
  bannerBar: {
    width: 3,
    borderRadius: 4,
    backgroundColor: COLORS.amberBorder,
    flexShrink: 0,
  },
  bannerText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.amber,
    lineHeight: 20,
  },

  // Card
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
    gap: 10,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 2,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
  },
  editBtn: {flexDirection: 'row', alignItems: 'center', gap: 4},
  editIcon: {fontSize: 14},
  editText: {fontSize: 13, fontWeight: '700', color: COLORS.teal},

  // Patient
  patientName: {fontSize: 15, fontWeight: '700', color: COLORS.textPrimary},
  patientReg: {fontSize: 13, color: COLORS.textSecondary},

  // Row
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rowLabel: {fontSize: 14, color: COLORS.textPrimary, flex: 1},
  rowLabelDim: {color: COLORS.textSecondary},
  rowValue: {fontSize: 14, color: COLORS.textPrimary, textAlign: 'right'},
  rowValueBold: {fontWeight: '800', fontSize: 16},

  // Dashed divider
  dashedDivider: {
    height: 1,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: COLORS.dashed,
    marginVertical: 2,
  },

  spacer: {height: 4},

  // Status
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  statusLabel: {fontSize: 14, color: COLORS.textSecondary},
  statusBadge: {
    backgroundColor: COLORS.tealLight,
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  statusBadgeText: {fontSize: 12, fontWeight: '700', color: COLORS.teal},

  // Bottom bar
  bottomBar: {
    backgroundColor: COLORS.bg,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 24,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  generateBtn: {
    backgroundColor: COLORS.teal,
    borderRadius: 16,
    paddingVertical: 17,
    alignItems: 'center',
    shadowColor: COLORS.teal,
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 4},
    elevation: 5,
  },
  generateBtnText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFF',
    letterSpacing: 0.1,
  },
  bottomNote: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
});
