import React, { useState, useEffect, useCallback } from "react";
import {
  View,
  Text,
  TextInput,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  Image,
  Alert,
  KeyboardAvoidingView,
  Platform,
} from "react-native";
import { launchImageLibrary } from "react-native-image-picker";
import RNFS from "react-native-fs";
import { useFocusEffect } from "@react-navigation/native";
import { getClinicSettings, saveClinicSettings } from "../../database";
import type { ClinicSettings } from "../../types";

import BASE from "./../../constants/colors";

const COLORS = {
  ...BASE,
  inputBg: "#FFFFFF",
  headerSub: "rgba(255,255,255,0.75)",
  saveBtn: "#2E7D72",
  footerText: "rgba(255,255,255,0.7)",
  footerBold: "#FFFFFF",
};

const DEFAULTS: ClinicSettings = {
  clinicName: "VedaMotion Care",
  tagline: "Where Every Move Heals",
  phone: "+91 8875115254",
  email: "vedamotioncare@gmail.com",
  website: "www.vedamotioncare.in",
  physiotherapist: "Dr. Yash Pratihasta, PT",
  patientIdFormat: "VMCPTREG-####",
  gst: "",
  logoUri: "",
  insuranceClause:
    "This is a valid e-bill generated by VedaMotion Care. To verify its authenticity, please email vedamotioncare@gmail.com quoting the invoice number. A confirmation will be sent after the bill is verified against our records.",
};

function FieldLabel({ label }: any) {
  return <Text style={styles.label}>{label}</Text>;
}

function Field({
  label,
  value,
  onChangeText,
  placeholder,
  keyboardType,
  multiline,
  numberOfLines,
}: any) {
  return (
    <View style={styles.fieldWrapper}>
      <FieldLabel label={label} />
      <TextInput
        style={[styles.input, multiline && styles.inputMultiline]}
        value={value}
        onChangeText={onChangeText}
        placeholder={placeholder || ""}
        placeholderTextColor={COLORS.placeholder}
        keyboardType={keyboardType || "default"}
        autoCapitalize="none"
        multiline={multiline}
        numberOfLines={numberOfLines}
        textAlignVertical={multiline ? "top" : "center"}
      />
    </View>
  );
}

export default function ClinicProfileScreen() {
  const [form, setForm] = useState<ClinicSettings>(DEFAULTS);
  const [loaded, setLoaded] = useState(false);

  const set = (key: keyof ClinicSettings) => (val: string) =>
    setForm((prev) => ({ ...prev, [key]: val }));

  useFocusEffect(
    useCallback(() => {
      (async () => {
        try {
          const saved = await getClinicSettings();
          if (saved) setForm(saved);
        } catch {}
        setLoaded(true);
      })();
    }, []),
  );

  const handleSave = async () => {
    try {
      await saveClinicSettings(form);
      Alert.alert("Saved", "Clinic profile updated successfully.");
    } catch (error: any) {
      Alert.alert("Error", error?.message || "Failed to save settings.");
    }
  };

  const handlePickLogo = () => {
    launchImageLibrary(
      { mediaType: "photo", quality: 0.8 },
      async (response) => {
        if (response.didCancel) return;
        if (response.errorCode) {
          Alert.alert(
            "Error",
            response.errorMessage || "Failed to pick image.",
          );
          return;
        }
        const asset = response.assets?.[0];
        const uri = asset?.uri;
        if (!uri) return;
        try {
          const ext = asset.fileName?.split(".").pop() || "jpg";
          const dest = `${RNFS.DocumentDirectoryPath}/clinic_logo.${ext}`;
          // Android 14+ returns content:// URIs; copyFile may fail with those.
          // Read as base64 and write to ensure the file is persisted.
          if (Platform.OS === "android" && uri.startsWith("content://")) {
            const base64 = await RNFS.readFile(uri, "base64");
            await RNFS.writeFile(dest, base64, "base64");
          } else {
            await RNFS.copyFile(uri, dest);
          }
          setForm((prev) => ({ ...prev, logoUri: `file://${dest}` }));
        } catch (err) {
          // Fallback: use original URI (may not persist on Android 14+)
          setForm((prev) => ({ ...prev, logoUri: uri }));
        }
      },
    );
  };

  return (
    <SafeAreaView style={styles.safe}>
      {/* <StatusBar barStyle="light-content" backgroundColor={COLORS.teal} /> */}

      <KeyboardAvoidingView
        style={{ flex: 1 }}
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        keyboardVerticalOffset={0}
      >
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Clinic Profile</Text>
          <Text style={styles.headerSub}>
            One-time setup — auto-applied to every invoice
          </Text>
        </View>

        <ScrollView
          style={styles.scroll}
          contentContainerStyle={styles.container}
          showsVerticalScrollIndicator={false}
          keyboardShouldPersistTaps="handled"
        >
          {/* Logo card */}
          <TouchableOpacity
            style={styles.logoCard}
            activeOpacity={0.7}
            onPress={handlePickLogo}
          >
            <View style={styles.logoBox}>
              {form.logoUri ? (
                <Image
                  source={{ uri: form.logoUri }}
                  style={styles.logoImage}
                />
              ) : (
                <Text style={styles.logoEmoji}>🌿</Text>
              )}
            </View>
            <View style={styles.logoInfo}>
              <Text style={styles.logoName}>{form.clinicName}</Text>
              <Text style={styles.logoHint}>Logo · tap to change</Text>
            </View>
            <TouchableOpacity
              style={styles.changeBtn}
              activeOpacity={0.8}
              onPress={handlePickLogo}
            >
              <Text style={styles.changeBtnText}>Change</Text>
            </TouchableOpacity>
          </TouchableOpacity>

          {/* Form fields */}
          <Field
            label="CLINIC NAME"
            value={form.clinicName}
            onChangeText={set("clinicName")}
          />
          <Field
            label="TAGLINE"
            value={form.tagline}
            onChangeText={set("tagline")}
          />

          {/* Phone + Email row */}
          <View style={styles.row}>
            <View style={styles.halfField}>
              <FieldLabel label="PHONE" />
              <TextInput
                style={styles.input}
                value={form.phone}
                onChangeText={set("phone")}
                keyboardType="phone-pad"
                placeholderTextColor={COLORS.placeholder}
              />
            </View>
            <View style={styles.halfField}>
              <FieldLabel label="EMAIL" />
              <TextInput
                style={styles.input}
                value={form.email}
                onChangeText={set("email")}
                keyboardType="email-address"
                autoCapitalize="none"
                placeholderTextColor={COLORS.placeholder}
              />
            </View>
          </View>

          <Field
            label="WEBSITE"
            value={form.website}
            onChangeText={set("website")}
            keyboardType="url"
          />
          <Field
            label="TREATING PHYSIOTHERAPIST"
            value={form.physiotherapist}
            onChangeText={set("physiotherapist")}
          />
          <Field
            label="PATIENT ID FORMAT"
            value={form.patientIdFormat}
            onChangeText={set("patientIdFormat")}
          />
          <Field
            label="GST / REGISTRATION NO. (OPTIONAL)"
            value={form.gst}
            onChangeText={set("gst")}
            placeholder="Leave blank if not applicable"
          />
          <Field
            label="INSURANCE VERIFICATION CLAUSE"
            value={form.insuranceClause}
            onChangeText={set("insuranceClause")}
            multiline
            numberOfLines={5}
          />

          {/* Save button */}
          <TouchableOpacity
            style={styles.saveBtn}
            activeOpacity={0.85}
            onPress={handleSave}
          >
            <Text style={styles.saveBtnText}>Save Changes</Text>
          </TouchableOpacity>

          {/* Footer note */}
          <Text style={styles.footer}>
            <Text style={styles.footerBold}>Clinic Profile</Text>
            {
              " — one-time setup pulled onto every PDF, so nothing is retyped per invoice."
            }
          </Text>
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: COLORS.teal,
  },

  // Header
  header: {
    backgroundColor: COLORS.teal,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: COLORS.headerText,
    letterSpacing: -0.5,
  },
  headerSub: {
    fontSize: 13,
    color: COLORS.headerSub,
    marginTop: 3,
  },

  // Scroll
  scroll: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  container: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 36,
    gap: 14,
  },

  // Logo card
  logoCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
    marginBottom: 4,
  },
  logoBox: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: COLORS.teal,
    alignItems: "center",
    justifyContent: "center",
  },
  logoEmoji: {
    fontSize: 24,
  },
  logoImage: {
    width: 52,
    height: 52,
    borderRadius: 12,
  },
  logoInfo: {
    flex: 1,
  },
  logoName: {
    fontSize: 15,
    fontWeight: "700",
    color: COLORS.textPrimary,
  },
  logoHint: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  changeBtn: {
    borderWidth: 1.5,
    borderColor: COLORS.teal,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  changeBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.teal,
  },

  // Field
  fieldWrapper: {
    gap: 6,
  },
  label: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.label,
    letterSpacing: 0.8,
  },
  input: {
    backgroundColor: COLORS.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 14,
    color: COLORS.textPrimary,
  },
  inputMultiline: {
    minHeight: 110,
    paddingTop: 13,
  },

  // Phone + email row
  row: {
    flexDirection: "row",
    gap: 10,
  },
  halfField: {
    flex: 1,
    gap: 6,
  },

  // Save button
  saveBtn: {
    backgroundColor: COLORS.teal,
    borderRadius: 14,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 6,
    shadowColor: COLORS.teal,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  saveBtnText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.2,
  },

  // Footer
  footer: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: "center",
    lineHeight: 18,
    paddingHorizontal: 8,
  },
  footerBold: {
    fontWeight: "700",
    color: COLORS.tealDark,
  },
});
