import React, {useState, useCallback} from 'react';
import {
  View,
  Text,
  TextInput,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  SafeAreaView,
  Image,
  KeyboardAvoidingView,
  Platform,
  Modal,
} from 'react-native';
import {launchImageLibrary} from 'react-native-image-picker';
import RNFS from 'react-native-fs';
import {useFocusEffect} from '@react-navigation/native';
import {getClinicSettings, saveClinicSettings} from '../../database';
import type {ClinicSettings} from '../../types';
import {
  Camera,
  Building2,
  Phone,
  Mail,
  Globe,
  Stethoscope,
  Hash,
  FileText,
  Shield,
  Save,
  Check,
  Tag,
  Pencil,
  X,
} from 'lucide-react-native';
import ReusableAlert from '../../components/ReusableAlert';
import {useReusableAlert} from '../../components/useReusableAlert';

import COLORS from '../../constants/colors';

const DEFAULTS: ClinicSettings = {
  clinicName: 'VedaMotion Care',
  tagline: 'Where Every Move Heals',
  phone: '+91 8875115254',
  email: 'vedamotioncare@gmail.com',
  website: 'www.vedamotioncare.in',
  physiotherapist: 'Dr. Yash Pratihasta, PT',
  patientIdFormat: 'VMCPTREG-####',
  gst: '',
  logoUri: '',
  insuranceClause:
    'This is a valid e-bill generated by VedaMotion Care. To verify its authenticity, please email vedamotioncare@gmail.com quoting the invoice number. A confirmation will be sent after the bill is verified against our records.',
};

function DisplayRow({
  label,
  value,
  icon: Icon,
}: {
  label: string;
  value: string;
  icon: any;
}) {
  return (
    <View style={styles.displayRow}>
      <View style={styles.fieldIcon}>
        <Icon size={16} color={COLORS.teal} strokeWidth={2} />
      </View>
      <Text style={styles.displayLabel}>{label}</Text>
      <Text style={styles.displayValue} numberOfLines={1}>
        {value || '—'}
      </Text>
    </View>
  );
}

function EditField({
  label,
  value,
  onChangeText,
  placeholder,
  keyboardType,
  icon: Icon,
}: {
  label: string;
  value: string;
  onChangeText: (v: string) => void;
  placeholder?: string;
  keyboardType?: string;
  icon: any;
}) {
  return (
    <View style={styles.editRow}>
      <View style={styles.editLabelRow}>
        <View style={styles.fieldIcon}>
          <Icon size={15} color={COLORS.teal} strokeWidth={2} />
        </View>
        <Text style={styles.editLabel}>{label}</Text>
      </View>
      <TextInput
        style={styles.editInput}
        value={value}
        onChangeText={onChangeText}
        placeholder={placeholder || ''}
        placeholderTextColor={COLORS.placeholder}
        keyboardType={(keyboardType as any) || 'default'}
        autoCapitalize="none"
      />
    </View>
  );
}

export default function ClinicProfileScreen() {
  const [form, setForm] = useState<ClinicSettings>(DEFAULTS);
  const [editForm, setEditForm] = useState<ClinicSettings>(DEFAULTS);
  const [modalVisible, setModalVisible] = useState(false);
  const [saving, setSaving] = useState(false);
  const {
    config,
    visible: alertVisible,
    showAlert,
    hideAlert,
  } = useReusableAlert();

  const setEdit = (key: keyof ClinicSettings) => (val: string) =>
    setEditForm(prev => ({...prev, [key]: val}));

  useFocusEffect(
    useCallback(() => {
      (async () => {
        try {
          const data = await getClinicSettings();
          if (data) {
            setForm(data);
            setEditForm(data);
          }
        } catch {}
      })();
    }, []),
  );

  const openEdit = () => {
    setEditForm({...form});
    setModalVisible(true);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveClinicSettings(editForm);
      setForm({...editForm});
      setModalVisible(false);
      showAlert({
        icon: '✅',
        title: 'Profile Updated',
        message: 'Clinic profile saved successfully.',
        buttons: [{text: 'OK'}],
      });
    } catch (error: any) {
      showAlert({
        icon: '⚠️',
        title: 'Error',
        message: error?.message || 'Failed to save settings.',
        buttons: [{text: 'OK'}],
      });
    } finally {
      setSaving(false);
    }
  };

  const handlePickLogo = () => {
    launchImageLibrary({mediaType: 'photo', quality: 0.8}, async response => {
      if (response.didCancel) return;
      if (response.errorCode) {
        showAlert({
          icon: '⚠️',
          title: 'Error',
          message: response.errorMessage || 'Failed to pick image.',
          buttons: [{text: 'OK'}],
        });
        return;
      }
      const asset = response.assets?.[0];
      const uri = asset?.uri;
      if (!uri) return;
      try {
        const ext = asset.fileName?.split('.').pop() || 'jpg';
        const dest = `${RNFS.DocumentDirectoryPath}/clinic_logo.${ext}`;
        if (Platform.OS === 'android' && uri.startsWith('content://')) {
          const base64 = await RNFS.readFile(uri, 'base64');
          await RNFS.writeFile(dest, base64, 'base64');
        } else {
          await RNFS.copyFile(uri, dest);
        }
        const newUri = `file://${dest}`;
        setForm(prev => ({...prev, logoUri: newUri}));
        setEditForm(prev => ({...prev, logoUri: newUri}));
      } catch {
        setForm(prev => ({...prev, logoUri: uri}));
        setEditForm(prev => ({...prev, logoUri: uri}));
      }
    });
  };

  const current = modalVisible ? editForm : form;

  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.header}>
        <Text style={styles.headerTitle}>Clinic Profile</Text>
        <Text style={styles.headerSub}>
          One-time setup — auto-applied to every invoice
        </Text>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}>
        {/* Hero */}
        <View style={styles.hero}>
          <View style={styles.heroAvatar}>
            {current.logoUri ? (
              <Image source={{uri: current.logoUri}} style={styles.heroImage} />
            ) : (
              <Building2 size={32} color={COLORS.teal} strokeWidth={1.5} />
            )}
          </View>
          <Text style={styles.heroName}>{current.clinicName}</Text>
          <Text style={styles.heroTagline}>{current.tagline}</Text>
        </View>

        {/* General */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>General Information</Text>
          <View style={styles.divider} />
          <DisplayRow
            label="Clinic Name"
            value={current.clinicName}
            icon={Building2}
          />
          <View style={styles.divider} />
          <DisplayRow label="Tagline" value={current.tagline} icon={Tag} />
          <View style={styles.divider} />
          <DisplayRow label="Website" value={current.website} icon={Globe} />
        </View>

        {/* Contact */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Contact Details</Text>
          <View style={styles.divider} />
          <DisplayRow label="Phone" value={current.phone} icon={Phone} />
          <View style={styles.divider} />
          <DisplayRow label="Email" value={current.email} icon={Mail} />
        </View>

        {/* Professional */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Professional</Text>
          <View style={styles.divider} />
          <DisplayRow
            label="Physiotherapist"
            value={current.physiotherapist}
            icon={Stethoscope}
          />
          <View style={styles.divider} />
          <DisplayRow
            label="Patient ID Format"
            value={current.patientIdFormat}
            icon={Hash}
          />
          <View style={styles.divider} />
          <DisplayRow
            label="GST / Reg. No."
            value={current.gst || 'Not set'}
            icon={FileText}
          />
        </View>

        {/* Legal */}
        <View style={styles.card}>
          <Text style={styles.cardTitle}>Legal & Compliance</Text>
          <View style={styles.divider} />
          <View style={styles.displayTextArea}>
            <View style={styles.editLabelRow}>
              <View style={styles.fieldIcon}>
                <Shield size={16} color={COLORS.teal} strokeWidth={2} />
              </View>
              <Text style={styles.displayLabel}>Insurance Clause</Text>
            </View>
            <Text style={styles.clauseText} numberOfLines={3}>
              {current.insuranceClause || 'Not set'}
            </Text>
          </View>
        </View>

        <Text style={styles.footer}>
          <Text style={styles.footerBold}>Clinic Profile</Text>
          {' is pulled onto every PDF — nothing is retyped per invoice.'}
        </Text>
      </ScrollView>

      {/* Sticky Edit Button */}
      <View style={styles.editBar}>
        <TouchableOpacity
          style={styles.editBtn}
          activeOpacity={0.85}
          onPress={openEdit}>
          <Pencil size={18} color="#FFFFFF" strokeWidth={2.5} />
          <Text style={styles.editBtnText}>Edit Profile</Text>
        </TouchableOpacity>
      </View>

      {/* Edit Modal */}
      <Modal
        visible={modalVisible}
        animationType="slide"
        presentationStyle="pageSheet"
        onRequestClose={() => setModalVisible(false)}>
        <SafeAreaView style={styles.modalSafe}>
          <KeyboardAvoidingView
            style={{flex: 1}}
            behavior={Platform.OS === 'ios' ? 'padding' : undefined}
            keyboardVerticalOffset={0}>
            {/* Modal Header */}
            <View style={styles.modalHeader}>
              <TouchableOpacity
                style={styles.modalClose}
                activeOpacity={0.7}
                onPress={() => setModalVisible(false)}>
                <X size={20} color={COLORS.textPrimary} strokeWidth={2.5} />
              </TouchableOpacity>
              <Text style={styles.modalTitle}>Edit Profile</Text>
              <TouchableOpacity
                activeOpacity={0.7}
                onPress={handleSave}
                disabled={saving}>
                <Text style={[styles.modalSave, saving && {opacity: 0.5}]}>
                  {saving ? 'Saving...' : 'Save'}
                </Text>
              </TouchableOpacity>
            </View>

            <ScrollView
              style={styles.modalScroll}
              contentContainerStyle={styles.modalScrollContent}
              showsVerticalScrollIndicator={false}
              keyboardShouldPersistTaps="handled">
              {/* Logo */}
              <TouchableOpacity
                style={styles.modalLogo}
                activeOpacity={0.8}
                onPress={handlePickLogo}>
                <View style={styles.modalLogoBox}>
                  {editForm.logoUri ? (
                    <Image
                      source={{uri: editForm.logoUri}}
                      style={styles.modalLogoImage}
                    />
                  ) : (
                    <Building2
                      size={28}
                      color={COLORS.teal}
                      strokeWidth={1.5}
                    />
                  )}
                  <View style={styles.modalCameraBadge}>
                    <Camera size={11} color="#FFF" strokeWidth={2.5} />
                  </View>
                </View>
                <Text style={styles.modalLogoHint}>Tap to change logo</Text>
              </TouchableOpacity>

              {/* General */}
              <View style={styles.modalCard}>
                <Text style={styles.modalCardTitle}>General</Text>
                <View style={styles.modalDivider} />
                <EditField
                  label="Clinic Name"
                  value={editForm.clinicName}
                  onChangeText={setEdit('clinicName')}
                  icon={Building2}
                />
                <View style={styles.modalDivider} />
                <EditField
                  label="Tagline"
                  value={editForm.tagline}
                  onChangeText={setEdit('tagline')}
                  icon={Tag}
                />
                <View style={styles.modalDivider} />
                <EditField
                  label="Website"
                  value={editForm.website}
                  onChangeText={setEdit('website')}
                  keyboardType="url"
                  icon={Globe}
                />
              </View>

              {/* Contact */}
              <View style={styles.modalCard}>
                <Text style={styles.modalCardTitle}>Contact</Text>
                <View style={styles.modalDivider} />
                <EditField
                  label="Phone"
                  value={editForm.phone}
                  onChangeText={setEdit('phone')}
                  keyboardType="phone-pad"
                  icon={Phone}
                />
                <View style={styles.modalDivider} />
                <EditField
                  label="Email"
                  value={editForm.email}
                  onChangeText={setEdit('email')}
                  keyboardType="email-address"
                  icon={Mail}
                />
              </View>

              {/* Professional */}
              <View style={styles.modalCard}>
                <Text style={styles.modalCardTitle}>Professional</Text>
                <View style={styles.modalDivider} />
                <EditField
                  label="Physiotherapist"
                  value={editForm.physiotherapist}
                  onChangeText={setEdit('physiotherapist')}
                  icon={Stethoscope}
                />
                <View style={styles.modalDivider} />
                <EditField
                  label="Patient ID Format"
                  value={editForm.patientIdFormat}
                  onChangeText={setEdit('patientIdFormat')}
                  icon={Hash}
                />
                <View style={styles.modalDivider} />
                <EditField
                  label="GST / Reg. No."
                  value={editForm.gst}
                  onChangeText={setEdit('gst')}
                  placeholder="Optional"
                  icon={FileText}
                />
              </View>

              {/* Legal */}
              <View style={styles.modalCard}>
                <Text style={styles.modalCardTitle}>Legal & Compliance</Text>
                <View style={styles.modalDivider} />
                <View style={styles.textareaRow}>
                  <View style={styles.editLabelRow}>
                    <View style={styles.fieldIcon}>
                      <Shield size={15} color={COLORS.teal} strokeWidth={2} />
                    </View>
                    <Text style={styles.editLabel}>Insurance Clause</Text>
                  </View>
                  <TextInput
                    style={styles.textarea}
                    value={editForm.insuranceClause}
                    onChangeText={setEdit('insuranceClause')}
                    placeholder="Insurance verification clause..."
                    placeholderTextColor={COLORS.placeholder}
                    multiline
                    textAlignVertical="top"
                  />
                </View>
              </View>

              <View style={{height: 40}} />
            </ScrollView>
          </KeyboardAvoidingView>
        </SafeAreaView>
      </Modal>

      <ReusableAlert
        visible={alertVisible}
        title={config?.title || ''}
        message={config?.message}
        icon={config?.icon}
        buttons={config?.buttons || []}
        onDismiss={hideAlert}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: {flex: 1, backgroundColor: COLORS.teal},

  header: {
    backgroundColor: COLORS.teal,
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 20,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: COLORS.headerText,
    letterSpacing: -0.5,
  },
  headerSub: {
    fontSize: 13,
    color: COLORS.headerSub,
    marginTop: 2,
  },

  scroll: {flex: 1, backgroundColor: COLORS.bg},
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 170,
    gap: 14,
  },

  // Hero
  hero: {
    alignItems: 'center',
    paddingVertical: 20,
    gap: 6,
  },
  heroAvatar: {
    width: 80,
    height: 80,
    borderRadius: 24,
    backgroundColor: COLORS.tealBg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 3,
    borderColor: COLORS.card,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 3},
    elevation: 3,
  },
  heroImage: {
    width: 80,
    height: 80,
    borderRadius: 24,
  },
  heroName: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
    letterSpacing: -0.3,
    marginTop: 4,
  },
  heroTagline: {
    fontSize: 13,
    color: COLORS.textSecondary,
  },

  // Card
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    paddingVertical: 4,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  cardTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textSecondary,
    letterSpacing: 0.4,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 6,
  },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.border,
    marginLeft: 48,
  },

  // Display row
  displayRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    height: 48,
    gap: 10,
  },
  fieldIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: COLORS.tealBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  displayLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: COLORS.textSecondary,
  },
  displayValue: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textPrimary,
    flex: 1.5,
    textAlign: 'right',
  },

  // Display textarea
  displayTextArea: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  clauseText: {
    fontSize: 13,
    color: COLORS.textPrimary,
    lineHeight: 20,
    paddingLeft: 40,
  },

  // Edit bar
  editBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: 90,
    paddingTop: 10,
    backgroundColor: COLORS.bg,
  },
  editBtn: {
    backgroundColor: COLORS.teal,
    borderRadius: 14,
    paddingVertical: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: COLORS.teal,
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 4},
    elevation: 4,
  },
  editBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },

  footer: {
    fontSize: 12,
    color: COLORS.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: 12,
  },
  footerBold: {
    fontWeight: '700',
    color: COLORS.tealDark,
  },

  // ---- Modal ----
  modalSafe: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: COLORS.card,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.border,
  },
  modalClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: COLORS.textPrimary,
  },
  modalSave: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.teal,
  },

  modalScroll: {flex: 1},
  modalScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 20,
    gap: 14,
  },

  // Modal logo
  modalLogo: {
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
  },
  modalLogoBox: {
    width: 68,
    height: 68,
    borderRadius: 20,
    backgroundColor: COLORS.tealBg,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: COLORS.card,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  modalLogoImage: {
    width: 68,
    height: 68,
    borderRadius: 20,
  },
  modalCameraBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.teal,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.bg,
  },
  modalLogoHint: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },

  // Modal card
  modalCard: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    paddingVertical: 4,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  modalCardTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textSecondary,
    letterSpacing: 0.4,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 6,
  },
  modalDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: COLORS.border,
    marginLeft: 48,
  },

  // Edit field row
  editRow: {
    paddingHorizontal: 14,
    gap: 6,
    paddingVertical: 10,
  },
  editLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  editLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.label,
  },
  editInput: {
    backgroundColor: COLORS.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 15,
    color: COLORS.textPrimary,
    marginLeft: 38,
  },

  // Textarea
  textareaRow: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    gap: 8,
  },
  textarea: {
    backgroundColor: COLORS.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 12,
    fontSize: 14,
    lineHeight: 20,
    color: COLORS.textPrimary,
    minHeight: 90,
    marginLeft: 38,
  },
});
